### ISSUE TITLE
Inject IFactory<T>() instead of IFactory<T>

### ISSUE THREAD

**Issue by ktersius** [inversify/InversifyJS#178] opened 2016-04-23 20:58 UTC
Lets say I have a factory that creates some instance of T. Now I would like to make T directly inject-able without having to inject the `IFactory<T>` and then calling `IFactory<T>()` to create my instance.

I'd like to be able to write the constructor as `(@inject("T") instance:T)` and inversify automatically calls `IFactory<T>()` for me and injects my new instance of T.

Assume the factory takes no arguments. Is this possible?

**Comment by remojansen** [comment] 2016-04-24 01:36
As it is right now it is not possible. When you request T InversifyJS will create an instance of T but it won't use `Factory<T>` for that. However, I will soon start working on a feature that will solve this problem and has been already being requested by other users. I will a new comment when I have an update. Sorry for any issues caused by the lack of this feature.

**Comment by remojansen** [comment] 2016-04-24 16:38
I'm closing this issue but you can follow the progress at  #177

**Closed as completed by remojansen** 2016-04-24 16:38 UTC
Labels: enhancement

**Comment by remojansen** [comment] 2016-04-25 09:22
#177 has been split into two issues. You can track the progress of the dynamic value injection in #181
