### ISSUE TITLE
Memory leak when using inversify within a jest test

### ISSUE THREAD

**Issue by lihue** [inversify/InversifyJS#1141] opened 2019-08-29 15:16 UTC
There is a memory leak when I'm using inversify within a jest test.

## Steps to Reproduce
Testcase: https://gist.github.com/lihue/c8afc4d5851cbc1a5fefd8bb84fe08bf
Run it with: jest --env=node --detectLeaks

## Expected Behavior
Test should run without any memory leak.

## Current Behavior
 Test suite failed to run

    Your test suite is leaking memory. Please ensure all references are cleaned.

    There is a number of things that can leak memory:
      - Async operations that have not finished (e.g. fs.readFile).
      - Timers not properly mocked (e.g. setInterval, setTimeout).
      - Keeping references to the global scope.

      at node_modules/@jest/core/build/TestScheduler.js:257:24
      at asyncGeneratorStep (node_modules/@jest/core/build/TestScheduler.js:131:24)
      at _next (node_modules/@jest/core/build/TestScheduler.js:151:9)
      at node_modules/@jest/core/build/TestScheduler.js:156:7
      at node_modules/@jest/core/build/TestScheduler.js:148:12
      at onResult (node_modules/@jest/core/build/TestScheduler.js:271:25)

## Environment
inversify: 5.0.1
inversify-express-utils: 6.3.2
jest: 24.9.0
supertest: 4.0.2

**Comment by GaelS** [comment] 2020-07-29 07:38
The leak seems to be fixed if you close the app after your test.
```
    afterAll(async (done) => {
       myApp.close(done);
    });
    
    /**
     ... 
     **/

    server = new InversifyExpressServer(container);
    const app = server.build();
    myApp = app.listen(3000);
    supertest(myApp).get("/").expect(200);

```

**Comment by notaphplover** [comment] 2024-11-25 01:18
Closing the issue as not related to inversify. The leak is caused by the server not being closed.

**Closed as completed by notaphplover** 2024-11-25 01:18 UTC
