### ISSUE TITLE
Middleware injection throw an error _Constructor already exists!_

### ISSUE THREAD

**Issue by MathieuDoyon** [inversify/InversifyJS#703] opened 2017-12-07 12:51 UTC
## Expected Behavior
It should able to go through the attach rectify middleware without throwing any error.

## Current Behavior
Currently, as soon I try to add a testify middleware is throw the error

## Steps to Reproduce (for bugs)
Clone the following repository https://github.com/MathieuDoyon/restify-inversify-errors
1.  install the dependencies 
2. run `npm run start:inversify`
3. you should get the error 
```
node_modules/restify-errors/lib/index.js:67
    assert.equal(typeof module.exports[name], 'undefined',
           ^
AssertionError [ERR_ASSERTION]: Constructor already exists!
```

## Your Environment
* Node v8.9.1
* restify@6.3.4
* @types/restify@5.0.6
* restify-errors@5.0.0
* @types/restify-errors@4.3.2
* inversify@4.6.0
* inversify-restify-utils@3.3.1

# Stack trace
```
/Users/mathieu.doyon/Developer/test/restify/node_modules/restify-errors/lib/index.js:67
    assert.equal(typeof module.exports[name], 'undefined',
           ^
AssertionError [ERR_ASSERTION]: Constructor already exists!
    at Object.makeConstructor (/Users/mathieu.doyon/Developer/test/restify/node_modules/restify-errors/lib/index.js:67:12)
    at Object.<anonymous> (/Users/mathieu.doyon/Developer/test/restify/node_modules/restify/lib/errorTypes.js:5:8)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mathieu.doyon/Developer/test/restify/node_modules/restify/lib/index.js:14:1)
```

**Comment by remojansen** [comment] 2017-12-07 14:25
I took a look but I was unable to find out what is wrong. It looks like it is a restify issue though...

The error is thrown when you import restify [here](https://github.com/MathieuDoyon/restify-inversify-errors/blob/master/src/App.ts#L5).

```ts
import * as restify from 'restify';
```

Importing restify will import `errorTypes.js` as you can see [here](https://github.com/MathieuDoyon/restify-inversify-errors/blob/master/src/App.ts#L5).

```js
require('./errorTypes');
```

The `errorTypes.js` file [leads us](https://github.com/restify/node-restify/blob/master/lib/errorTypes.js#L5-L6) to `restify-errors`:

```js
'use strict';

var errors = require('restify-errors');

errors.makeConstructor('RequestCloseError');
errors.makeConstructor('RequestAbortedError');
```

And in `restify-errors` we can find [the place](https://github.com/restify/errors/blob/master/lib/index.js#L67-L68) in which the exception is thrown:

```js
function makeConstructor(name, defaults) {

    assert.string(name, 'name');
    assert.optionalObject(defaults, 'defaults');

    // code property doesn't have 'Error' in it. remove it.
    var defaultCode = name.replace(new RegExp('[Ee]rror$'), '');
    var d = _.assign({}, {
        name: name,
        code: (defaults && defaults.code) || defaultCode,
        restCode: _.get(defaults, 'restCode', defaultCode)
    }, defaults);

    // assert that this constructor doesn't already exist.
    assert.equal(typeof module.exports[name], 'undefined',
                 'Constructor already exists!');
// ...
```

I was debugging and I saw that the function `makeConstructor` in `` is invoked tree times:

```js
errors.makeConstructor('RequestCloseError');
errors.makeConstructor('RequestAbortedError');

errors.makeConstructor('RequestCloseError'); // Error!!!
```

Something invoking `makeConstructor` two times with the id `"RequestCloseError"`. Which lead me to think that there is a weird issue in your app.

I have created a PR for your repo https://github.com/MathieuDoyon/restify-inversify-errors/pull/1 as you can see removing the import:

```ts
import * as restify from 'restify';
```
Fixes the problem. I actually tested something else and the problem is not the import, is the `pre` call:

```ts
import * as restify from 'restify'; // OK

const pre = restify.pre; // Exception
```
I'm sorry I don't know what is happening :(

**Comment by dropdevcoding** [comment] 2017-12-12 09:53
Probably this will help your investigation:
With
```
inversify: 4.6.0
inversify-restify-utils: 3.3.1
restify: 5.2.1
```
the error does not occur
when upgrading to 
```
restify: 6.3.4
```
I'm getting the same error

**Comment by remojansen** [comment] 2017-12-15 16:04
Hi @MathieuDoyon  can please try to upgrade to `restify@6.3.4` and let us know if this issue can be closed? I will close it in a few days if there are no updates.

**Closed as completed** 2017-12-17 00:10 UTC
