### ISSUE TITLE
Broken MongoDB Express example

### ISSUE THREAD

**Issue by lholznagel** [inversify/InversifyJS#283] opened 2016-06-30 06:44 UTC
## Expected Behavior

The server should start
## Current Behavior

When trying to start the server I get the message like it is in the Stack trace
## Possible Solution

When changing the Symbol back to a string `Symbol('Controller') -> 'Controller'` than everything works fine
## Steps to Reproduce (for bugs)

1. Clone project
2. run `ts-node MongoDB/bootstrap`
## Your Environment

- Version used: Master
- Environment name and version (e.g. Chrome 39, node.js 5.4): Node 6.2.0
- Operating System and version (desktop or mobile): Ubuntu 16.04
- Link to your project: https://github.com/inversify/inversify-express-example
# Stack trace

```
/path/to/project/inversify-express-example/node_modules/inversify/lib/kernel/kernel.js:169
                throw new Error(ERROR_MSGS.NOT_REGISTERED + " " + this.getServiceIdentifierAsString(serviceIdentifier));
                      ^
Error: No bindings found for serviceIdentifier: Controller
    at Kernel._getActiveBindings (/path/to/project/inversify-express-example/node_modules/inversify/lib/kernel/kernel.js:169:23)
    at Kernel._plan (/path/to/project/inversify-express-example/node_modules/inversify/lib/kernel/kernel.js:186:29)
    at Kernel._planAndResolve (/path/to/project/inversify-express-example/node_modules/inversify/lib/kernel/kernel.js:157:29)
    at Kernel._get (/path/to/project/inversify-express-example/node_modules/inversify/lib/kernel/kernel.js:149:27)
    at Kernel.getAll (/path/to/project/inversify-express-example/node_modules/inversify/lib/kernel/kernel.js:136:21)
    at InversifyExpressServer.registerControllers (/path/to/project/inversify-express-example/node_modules/inversify-express-utils/lib/server.js:34:39)
    at InversifyExpressServer.build (/path/to/project/inversify-express-example/node_modules/inversify-express-utils/lib/server.js:26:14)
    at Object.<anonymous> (bootstrap.ts:37:18)
    at Module._compile (module.js:541:32)
    at Object.loader (/usr/local/lib/node_modules/ts-node/src/ts-node.ts:225:14)
```

**Comment by remojansen** [comment] 2016-06-30 07:07
This is the error that I was expecting to happen based on the docs:

> The reflect-metadata polyfill should be imported only once in your entire application because the Reflect object is mean to be a global singleton.

This issue was reported [here](https://github.com/inversify/InversifyJS/issues/262#issuecomment-227593844) the problem is the usage of multiple `import 'reflect-metadata'` but yesterday I tried to remove them and it didn't work.

I think we need to remove all the `import 'reflect-metadata'` and leave only the ones in the bootstrap files. The problem them will happen when you run your unit tests. All the tests (in one application) need to run in the same process.

**Comment by lholznagel** [comment] 2016-06-30 07:10
Oh, got it. Completely forgot about metadata.

**Comment by lholznagel** [comment] 2016-06-30 07:31
Maybe I have an idea for the `reflect-metadata` problem. Because every module needs the main inversify project as dependency we can let the other modules access the main project. So how about we add a small api in the main project where all other modules register their decorators. With that only one module would create an instance of `reflect-metadata`.

Don´t now if this could work, will take a small look.

**Comment by lholznagel** [comment] 2016-06-30 09:17
Internally everything works, but when I try it in my project it breaks again :(.
Maybe the solution from inversify/inversify-express-example#9 is ok for the moment. Long term there must be another solution :D

**Comment by remojansen** [comment] 2016-06-30 09:48
I have plans to try to solve the reflect-metadata issue but is not that easy because we need a a browser and a node.js version. 

There is more details at https://github.com/inversify/InversifyJS/blob/master/wiki/module_bundlers.md

**Comment by lholznagel** [comment] 2016-06-30 09:51
Would help, but I completely avoid gulp, grunt, webpack, and so on. My setup uses TypeScript from start to end without any of these things. Only npm scripts :)

**Comment by remojansen** [comment] 2016-06-30 10:03
I'm happy to use npm script only but if the build is complex I find gulp easier to deal with.

**Comment by remojansen** [comment] 2016-07-05 00:58
Fix merged 🎉

**Closed as completed by remojansen** 2016-07-05 00:58 UTC
