### ISSUE TITLE
support for resolvable

### ISSUE THREAD

**Issue by tenowg** [inversify/InversifyJS#244] opened 2016-06-14 03:20 UTC
## Expected Behavior

Ability to tell if a Symbol/identifier would resolve, and maybe what it would resolve too.
## Possible Solution

canGet<T>(identifier: string | Symol | INewable<T>): class/object that would be resolved without actually resolving | null. 
## Context

There are times, as in my case, where items are added to the DI and later need to be checked against to see if they are already bound, preventing rebinding. Also to check if item is bound to prevent attempting to load an optional object manually.

This can be done now with a try/catch, but I like to avoid these as much as possible.

**Comment by remojansen** [comment] 2016-06-15 09:13
I can add something that would be fast to tell if a symbol/identifier has been registered. But not if it can be resolved. What I mean is that maybe resolving causes an exception (e.g. ambiguous binding) the only way to tell this or tell what it will resolve to is to actually resolve it. The problem is that resolving it would be much slower than checking if it is registered so it makes no sense to check if can be resolved when checking and resolving are the same thing. So I suggest we only check if it it registered but avoid resolving it. Would that be OK?

**Comment by tenowg** [comment] 2016-06-15 12:21
The main thing would be to check if it is registered, so this is fine.

**Comment by remojansen** [comment] 2016-06-16 23:06
This [is now implemented](https://github.com/inversify/InversifyJS/blob/master/wiki/get_all_named_tagged.md#kernelisbound) but not released yet.

**Closed as completed by remojansen** 2016-06-16 23:06 UTC
Labels: enhancement, semver: minor
