### ISSUE TITLE
Add support for typings field in package.json

### ISSUE THREAD

**Issue by otbe** [inversify/InversifyJS#186] opened 2016-04-29 10:56 UTC
Hi,

at this time (beta1) it is a mess to get typings for inversify, because `typings` installs an old alpha version.

Why you don't use the `typings` field in `package.json` ?

```
{
   ...,
   "typings": "type_definitions/inversify/inversify.d.ts",
}
```

It seems some build setup has to be changed to get this working, but its worth it :)

**Comment by remojansen** [comment] 2016-04-29 11:28
The [TypeScript docs](http://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html) explain the requirements for typed npm modules:

> Your definition files should
> - be.d.ts files
> - be written as external modules
> - not contain triple-slash references

The problem is that our type definitions [contain triple-slash](https://github.com/inversify/InversifyJS/blob/master/type_definitions/inversify/inversify.d.ts#L6-L7) references so we cant use the `typings` field:

Microsoft is working on a new way to publish type definitions via npm for TypeScript 2.0 so I will wait for that to be announced and do it the way they recommend.

**Comment by otbe** [comment] 2016-04-29 14:34
That sounds reasonable. :)
Thanks for clarification 👍

**Comment by remojansen** [comment] 2016-05-19 11:09
I have created [inversify-dts](https://www.npmjs.com/package/inversify-dts) that is the way we are going to provide type definitions for now so I'm closing this issue.

**Closed as completed by remojansen** 2016-05-19 11:09 UTC
Labels: semver: patch
