### ISSUE TITLE
number of constructor arguments must be >= ... the base class - when not overriding constructor

### ISSUE THREAD

**Issue by matthewjh** [inversify/InversifyJS#729] opened 2017-12-23 22:53 UTC
```ts
@injectable()
export class PluginRegistry {
  constructor (private readonly autoFactory: AutoFactory) {
  }
}

@injectable()
export class ApplicationPluginRegistryMain extends PluginRegistry {
}

container.resolve(ApplicationPluginRegistryMain); // throws
```

```
Error: The number of constructor arguments in the derived class ApplicationPluginRegistryMain must be >= than the number of constructor arguments of its base class.
```

It seems like a bug to throw this in cases where the derived class ***doesn't*** provide its own constructor, because intuitively the derived class would defer to its parent class's constructor. This is a problem for me because I'd like users to be able to drop new classes into my system without them needing to provide their own constructors (I don't want them to have to care about what injectables the base class needs).

**Comment by btkostner** [comment] 2017-12-30 04:46
Looking at [the code](https://github.com/inversify/InversifyJS/blob/master/src/planning/reflection_utils.ts#L55), it seems this is by design.

>  // Throw if a derived class does not implement its constructor explicitly
>  // We do this to prevent errors when a base class (parent) has dependencies
>  // and one of the derived classes (children) has no dependencies

**Comment by remojansen** [comment] 2018-01-02 14:50
Hi @matthewjh this is by design as reported by @btkostner but there are a few way to solve this problem as documented in [our wiki](https://github.com/inversify/InversifyJS/blob/master/wiki/inheritance.md) I will close this issue but please feel free to create a new one if you have more questions.

**Closed as completed by remojansen** 2018-01-02 14:50 UTC

**Comment by rweads0520** [comment] 2020-02-03 17:57
None of the workarounds I saw seemed to give me what I wanted, which I think is the same thing you're wanting. In my case, just adding @optional() to the base class constructor parameter gets rid of the error, and the parameter is correctly injected when resolving the derived class from the container.

```typescript
@injectable()
export class PluginRegistry {
  constructor (@optional() private readonly autoFactory: AutoFactory) {
  }
}

@injectable()
export class ApplicationPluginRegistryMain extends PluginRegistry {
}

container.resolve(ApplicationPluginRegistryMain); // ok now
```
