### ISSUE TITLE
`this` undefined when injected.

### ISSUE THREAD

**Issue by forrest-keller** [inversify/InversifyJS#1313] opened 2021-04-24 20:49 UTC
## Expected Behavior

Dependency injection should create object where `this` is defined.

## Current Behavior

When injecting dependency, `this` becomes undefined, leading to the following error:
```
TypeError: Cannot read property 'tokensService' of undefined
```

## Possible Solution

No clue.

## Steps to Reproduce (for bugs)

[Code available here.](https://github.com/bleep/api)

## Context

I am unable to run the API, as I cannot inject services.

## Your Environment

* Version used: 5.0.5
* Environment name and version (e.g. Chrome 39, node.js 5.4): NodeJS 15.14.0
* Operating System and version (desktop or mobile): Arch Linux 
* Link to your project: https://github.com/bleep/api

# Stack trace

```
TypeError: Cannot read property 'tokensService' of undefined
    at /home/forrest-keller/docs/code/projects/bleep/api/src/controllers/tokens.ts:30:27
    at Generator.next (<anonymous>)
    at /home/forrest-keller/docs/code/projects/bleep/api/src/controllers/tokens.ts:36:71
    at new Promise (<anonymous>)
    at __awaiter (/home/forrest-keller/docs/code/projects/bleep/api/src/controllers/tokens.ts:32:12)
    at post (/home/forrest-keller/docs/code/projects/bleep/api/src/controllers/tokens.ts:49:16)
    at dispatch (/home/forrest-keller/docs/code/projects/bleep/api/node_modules/koa-compose/index.js:42:32)
    at /home/forrest-keller/docs/code/projects/bleep/api/node_modules/koa-router/lib/router.js:372:16
    at dispatch (/home/forrest-keller/docs/code/projects/bleep/api/node_modules/koa-compose/index.js:42:32)
    at /home/forrest-keller/docs/code/projects/bleep/api/node_modules/koa-body/index.js:148:14
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at cors (/home/forrest-keller/docs/code/projects/bleep/api/node_modules/@koa/cors/index.js:98:16) {
  headers: {
    'Access-Control-Allow-Origin': 'http://localhost:3000',
    vary: 'Origin'
  }
```
}

**Comment by notaphplover** [comment] 2021-04-24 22:23
Hi @forrest-keller I'm trying to recreate the bug. As fas as I see, it seems to be circular dependencies which are not allowed:

```
npm run dev
```

```
Error: Circular dependency found: Symbol(UsersController) --> Symbol(UsersService) --> Symbol(EmailsService) --> Symbol(VerificationsService) --> Symbol(EmailsService)
    at /home/random/Documentos/Repos/api/node_modules/inversify/lib/utils/serialization.js:66:19
    at Array.forEach (<anonymous>)
    at circularDependencyToException (/home/random/Documentos/Repos/api/node_modules/inversify/lib/utils/serialization.js:63:27)
    at /home/random/Documentos/Repos/api/node_modules/inversify/lib/utils/serialization.js:69:13
    at Array.forEach (<anonymous>)
    at circularDependencyToException (/home/random/Documentos/Repos/api/node_modules/inversify/lib/utils/serialization.js:63:27)
    at /home/random/Documentos/Repos/api/node_modules/inversify/lib/utils/serialization.js:69:13
    at Array.forEach (<anonymous>)
    at circularDependencyToException (/home/random/Documentos/Repos/api/node_modules/inversify/lib/utils/serialization.js:63:27)
    at /home/random/Documentos/Repos/api/node_modules/inversify/lib/utils/serialization.js:69:13
    at Array.forEach (<anonymous>)
    at Object.circularDependencyToException (/home/random/Documentos/Repos/api/node_modules/inversify/lib/utils/serialization.js:63:27)
    at Object.plan (/home/random/Documentos/Repos/api/node_modules/inversify/lib/planning/planner.js:143:33)
    at /home/random/Documentos/Repos/api/node_modules/inversify/lib/container/container.js:319:37
    at Container._get (/home/random/Documentos/Repos/api/node_modules/inversify/lib/container/container.js:312:44)
    at Container.get (/home/random/Documentos/Repos/api/node_modules/inversify/lib/container/container.js:232:21)

```

I'm glad to help you, could you provide a [minimal reproducible scenario](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by forrest-keller** [comment] 2021-04-24 22:28
Hi @notaphplover, thanks for looking into this. I totally forgot to push a change that patched that issue. The circular dependency should not be an issue any more. I tried to create a minimal reproduction, but was unable to replicate the issue. It seems to be some configuration of mine, but I cannot figure out what.

**Comment by notaphplover** [comment] 2021-04-24 23:02
Hi @forrest-keller I added a `minimun-script.ts` file to test the container generation:

```ts
import container from './container';
import { TYPES } from './types';

const controller = container.get(TYPES.TokensController);

console.log(controller);
```

Eveything seems to be all right:

![image](https://user-images.githubusercontent.com/16786032/115974992-574ce500-a561-11eb-8b3f-8601434a7dad.png)

The `tokenService` property is injected. I am having hard times to recreate it since I do not have env variables nor a mongodb database. Could you add a docker-compose and an .env.sample file? Or at least some docs to build the project

**Comment by forrest-keller** [comment] 2021-04-24 23:15
Sorry @notaphplover for not preparing my repository adequately for this issue. I created a `.env.sample` in the repo.

**Comment by notaphplover** [comment] 2021-04-24 23:22
Don't worry, I'll have a look tomorrow :)

**Comment by notaphplover** [comment] 2021-04-25 08:02
Hi @forrest-keller, after having a look the problem is not related to `inversify`. You are passing controller functions to the router without binding them so `this` is undefined:

```ts
router
  .post("/users", usersController.post)
  .post("/tokens", tokensController.post)
  .post("/verifications", verificationsController.post)
  .delete("/verifications/:verificationId", verificationsController.deleteOne)
  .post("/recoveries", recoveriesController.post)
  .delete("/recoveries/:recoveryId", recoveriesController.deleteOne);
```

```ts
router
  .post("/users", usersController.post.bind(usersController))
  .post("/tokens", tokensController.post.bind(tokensController))
  .post(
    "/verifications",
    verificationsController.post.bind(verificationsController)
  )
  .delete(
    "/verifications/:verificationId",
    verificationsController.deleteOne.bind(verificationsController)
  )
  .post("/recoveries", recoveriesController.post.bind(recoveriesController))
  .delete(
    "/recoveries/:recoveryId",
    recoveriesController.deleteOne.bind(recoveriesController)
  );
```

I'm glad to help you @forrest-keller, but this kind of issues should be posted on stackoverflow. If you are sure you are facing a bug related to inversify, posting an issue here is the right decission. I don't mean to be rude but it's hard for us to help everyone on their projects (I wish I had time to do it). I'm closing the issue now, if you think anything else should be discussed just ping me and I'll reopen the issue :smiley:

**Closed as completed by notaphplover** 2021-04-25 08:03 UTC
